### ISSUE TITLE
打卡后无法自动切回助手

### ISSUE THREAD

**Issue by wekingchen** [SmileZXLee/uni-dingTalkHelper#3]
iPhone6 iOS12.5.5，打卡之后无法自动切回助手，手机会停在钉钉界面，时间久了就黑屏锁屏了。能帮忙看看是什么原因吗？

**Comment by SmileZXLee** [comment]
受系统限制，只能实现单次打卡，因为应用没有权限自己跳回来。

**Comment by wekingchen** [comment]
感谢回复，明白了。那只能每天下班设一次，为第二天早上做好准备咯~下班卡都无所谓了

**Comment by SmileZXLee** [comment]
> 感谢回复，明白了。那只能每天下班设一次，为第二天早上做好准备咯~下班卡都无所谓了

嗯嗯

**Comment by GrantLiu1** [comment]
安卓的机器也一样不行吗？
