### ISSUE TITLE
没有ipa吗

### ISSUE THREAD

**Issue by wuge0** [SmileZXLee/uni-dingTalkHelper#4]
想用TrollStore安装

**Comment by SmileZXLee** [comment]
如果需要ipa可以访问[https://github.com/SmileZXLee/OpenDingTalkHelperForiOS](https://github.com/SmileZXLee/OpenDingTalkHelperForiOS)

**Comment by wuge0** [comment]
> 如果需要ipa可以访问[https://github.com/SmileZXLee/OpenDingTalkHelperForiOS](https://github.com/SmileZXLee/OpenDingTalkHelperForiOS)

好吧
